dist: bionic
language: cpp

git:
 depth: 3

cache:
 ccache: true
 cargo: true
 directories:
  - ${HOME}/.mozbuild
  - ${HOME}/.cargo
  - ${HOME}/.rustup

install:
- cp taintfox_mozconfig_spidermonkey .mozconfig
- ./mach bootstrap --application-choice=browser --no-interactive
- sudo pip install six

script:
- ./mach build
- obj-spider-release/dist/bin/js js/src/Y.js
- js/src/tests/jstests.py obj-spider-release/dist/bin/js taint
