language: cpp

services:
  - docker

git:
  - depth: 3

before_install:
  - docker build -t taintfox-dev --target taintfox-dev dockerfiles

install:
  - true

script:
  - docker run --name taintfox-build -v $TRAVIS_BUILD_DIR:/usr/local/src/taintfox taintfox-dev
