# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update

      # Bootstrap
      - name: Bootstrap Build Environment
        run: |
          ./mach bootstrap --application-choice=browser
          /home/runner/.cargo/bin/rustup install 1.65.0
          /home/runner/.cargo/bin/rustup default 1.65.0
          /home/runner/.cargo/bin/rustup override set 1.65.0

      # Configure
      - name: Copy configuration
        run: |
          echo "mk_add_options MOZ_PARALLEL_BUILD=1" >> .mozconfig
          echo "ac_add_options --disable-sandbox" >> .mozconfig
          echo "ac_add_options --disable-updater" >> .mozconfig
          ./mach configure

      # Build
      - name: Build
        run: ./mach build

      # Test
      - name: Test
        run: ./mach test --headless  --log-xunit test-xunit.xml  taint/

  # This workflow contains a single job called "build"
  build_js:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update

      # Bootstrap
      - name: Bootstrap Build Environment
        run: ./mach bootstrap --application-choice=browser

      # Configure
      - name: Copy configuration
        run: cp taintfox_mozconfig_spidermonkey .mozconfig
      # Build
      - name: Build
        run: ./mach build

      # Test
      - name: Test
        run: obj-spider-release/dist/bin/js js/src/Y.js

      - name: Taint Tests
        run: js/src/tests/jstests.py obj-spider-release/dist/bin/js taint/

